## nameOverride String to partially override common.names.fullname
##
nameOverride: ""

## fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""

## pod parameters All things pod related
pod:

  # pod.replicaCount keep this to 1
  replicaCount: 1
  # pod.securityContext if using
  securityContext: {}
  livenessProbe:
    ## pod.livenessProbe.enabled enabled or not
    enabled: true
  ## pod.image.repository path to container image
  ## pod.image.tag tag of container image
  ## pod.image.pullPolicy pullPolicy
  image:
    repository: ghcr.io/dockur/samba
    tag: 4.22.6
    pullPolicy: IfNotPresent
  volumeMounts:
  - mountPath: /storage
    name: storage
  #- mountPath: /data
  #  name: data
  volumes:
  - name: storage
    emptyDir: {}
  #- name: data
  #  persistentVolumeClaim:
  #    claimName: data
  volumeClaimTemplates:
  #- metadata:
  #    name: mp3
  #  spec:
  #    accessModes: ["ReadWriteOnce"]
  #    resources:
  #      requests:
  #        storage: 120Gi
  #    storageClassName: "zfs"
  ## pod.resources standard k8s stuff
  resources: {}
  ## pod.nodeSelector standard k8s stuff
  nodeSelector: {}
  ## pod.tolerations standard k8s stuff
  tolerations: []
  ## pod.affinity standard k8s stuff
  affinity: {}

## @section service parameters
service:
  ## service.type type of service
  type: ClusterIP
  ## service.port port of service
  port: 445
  ## service.annotations annotations if using
  annotations: {}
