## nameOverride String to partially override common.names.fullname
##
nameOverride: ""

## fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""

## pod parameters All things pod related
pod:

  # pod.replicaCount keep this to 1
  replicaCount: 1
  # pod.securityContext if using
  securityContext: {}
  livenessProbe:
    ## pod.livenessProbe.enabled enabled or not
    enabled: true
  ## pod.image.repository path to container image
  ## pod.image.tag tag of container image
  ## pod.image.pullPolicy pullPolicy
  image:
    repository: ghcr.io/dockur/samba
    tag: 4.22.6
    pullPolicy: IfNotPresent
  ## pod.persistence.enabled whether to mount persistent storage
  ## pod.persistence.type one of other or pvcs
  ## pod.persistence.pvcs if type pvcs fill with sets of name, mountPath, size, storageClassName
  persistence:
    enabled: false
    type: other
    pvcs:
    - name: data
      mountPath: /data
      size: 8Gi
      storageClassName: "data"
  ## pod.useExistingSmbConfigmap if using or not
  useExistingSmbConfigmap: false
  ## pod.ExistingSmbConfigmap  name of configmap to mount. The filename should be smb.conf.
  ExistingSmbConfigmap: "smbconf" 
  ## pod.useExistingUsersSecret set to true if using
  useExistingUsersSecret: false
  ## pod.ExistingUsersSecret name of secret to mount. The filename should be users.conf. See https://github.com/dockur/samba
  ExistingUsersSecret: "users"
  ## pod.resources standard k8s stuff
  resources: {}
  ## pod.nodeSelector standard k8s stuff
  nodeSelector: {}
  ## pod.tolerations standard k8s stuff
  tolerations: []
  ## pod.affinity standard k8s stuff
  affinity: {}

## @section service parameters
service:
  ## service.type type of service
  type: ClusterIP
  ## service.port port of service
  port: 445
  ## service.annotations annotations if using
  annotations: {}

